# Generated by Django 3.0.1 on 2020-03-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_auto_20200308_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=10)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('day', models.CharField(max_length=20)),
                ('Lec', models.CharField(max_length=50)),
                ('type_of', models.CharField(max_length=20)),
            ],
        ),
    ]
