# Generated by Django 3.0.1 on 2020-03-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='Batch',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
