# Generated by Django 3.0.1 on 2020-03-14 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_first_name', models.CharField(max_length=100)),
                ('Student_middle_name', models.CharField(max_length=100)),
                ('Student_last_name', models.CharField(max_length=100)),
                ('Student_gender', models.CharField(max_length=100)),
                ('Student_email', models.EmailField(max_length=100)),
                ('Student_dob', models.DateField(blank=True)),
                ('Student_division', models.CharField(max_length=50)),
                ('Student_card', models.CharField(max_length=50)),
                ('Parent_first_name', models.CharField(max_length=100)),
                ('Parent_middle_name', models.CharField(max_length=100)),
                ('Parent_last_name', models.CharField(max_length=100)),
                ('Parent_email', models.EmailField(blank=True, max_length=100)),
                ('Parent_phone', models.IntegerField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
