# Generated by Django 3.0.1 on 2020-03-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200314_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='Student_card',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
