# Generated by Django 3.0.1 on 2020-03-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200315_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='Student_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
