# Generated by Django 3.0.1 on 2020-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200315_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='Parent_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Parent_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Parent_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Parent_middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Parent_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Student_division',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Student_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Student_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Student_gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Student_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='Student_middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
