# Generated by Django 3.0.1 on 2020-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200315_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='Batch',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
