# Generated by Django 3.0.1 on 2020-03-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20200320_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='Today_date',
            field=models.DateField(),
        ),
    ]
