# Generated by Django 3.0.1 on 2020-03-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_auto_20200320_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='Today_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
